2011-06-16 08:55:07,427 - INFO - Starting
2011-06-16 08:55:16,255 - INFO - Starting
2011-06-16 08:55:20,883 - ERROR - Genshi template Error
Traceback (most recent call last):
  File "flunkymaster.py", line 199, in render_image_path
    return tmpl.generate(**bvars).render('text')
  File "/usr/local/lib/python2.7/dist-packages/Genshi-0.6-py2.7.egg/genshi/core.py", line 183, in render
    return encode(generator, method=method, encoding=encoding, out=out)
  File "/usr/local/lib/python2.7/dist-packages/Genshi-0.6-py2.7.egg/genshi/output.py", line 57, in encode
    return _encode(''.join(list(iterator)))
  File "/usr/local/lib/python2.7/dist-packages/Genshi-0.6-py2.7.egg/genshi/output.py", line 569, in __call__
    for event in stream:
  File "/usr/local/lib/python2.7/dist-packages/Genshi-0.6-py2.7.egg/genshi/core.py", line 288, in _ensure
    for event in stream:
  File "/usr/local/lib/python2.7/dist-packages/Genshi-0.6-py2.7.egg/genshi/template/base.py", line 605, in _include
    for event in stream:
  File "/usr/local/lib/python2.7/dist-packages/Genshi-0.6-py2.7.egg/genshi/template/base.py", line 565, in _flatten
    result = _eval_expr(data, ctxt, vars)
  File "/usr/local/lib/python2.7/dist-packages/Genshi-0.6-py2.7.egg/genshi/template/base.py", line 277, in _eval_expr
    retval = expr.evaluate(ctxt)
  File "/usr/local/lib/python2.7/dist-packages/Genshi-0.6-py2.7.egg/genshi/template/eval.py", line 178, in evaluate
    return eval(self.code, _globals, {'__data__': data})
  File "<string>", line 22, in <Expression u'IMAGE'>
  File "/usr/local/lib/python2.7/dist-packages/Genshi-0.6-py2.7.egg/genshi/template/eval.py", line 309, in lookup_name
    val = cls.undefined(name)
  File "/usr/local/lib/python2.7/dist-packages/Genshi-0.6-py2.7.egg/genshi/template/eval.py", line 410, in undefined
    raise UndefinedError(key, owner=owner)
UndefinedError: "IMAGE" not defined
2011-06-16 08:57:42,619 - INFO - Starting
2011-06-16 08:57:45,546 - ERROR - Get failure
Traceback (most recent call last):
  File "flunkymaster.py", line 231, in __call__
    template = self.render_image_path(address, path)
  File "flunkymaster.py", line 192, in render_image_path
    bvars = self.build_vars(address, toRender)
  File "flunkymaster.py", line 122, in build_vars
    data.update(build_var)
ValueError: dictionary update sequence element #0 has length 1; 2 is required
2011-06-16 08:57:56,005 - ERROR - Get failure
Traceback (most recent call last):
  File "flunkymaster.py", line 231, in __call__
    template = self.render_image_path(address, path)
  File "flunkymaster.py", line 192, in render_image_path
    bvars = self.build_vars(address, toRender)
  File "flunkymaster.py", line 122, in build_vars
    data.update(build_var)
ValueError: dictionary update sequence element #0 has length 1; 2 is required
2011-06-16 08:57:56,845 - ERROR - Get failure
Traceback (most recent call last):
  File "flunkymaster.py", line 231, in __call__
    template = self.render_image_path(address, path)
  File "flunkymaster.py", line 192, in render_image_path
    bvars = self.build_vars(address, toRender)
  File "flunkymaster.py", line 122, in build_vars
    data.update(build_var)
ValueError: dictionary update sequence element #0 has length 1; 2 is required
2011-06-16 08:59:31,794 - INFO - Starting
2011-06-16 09:01:12,489 - INFO - Starting
