2011-06-14 17:28:29,660 - ERROR - Failed to load datafile /home/mike/flunky/repository/backup/data.json
2011-06-14 17:28:29,660 - INFO - Starting
2011-06-15 11:50:57,834 - INFO - Starting
2011-06-15 11:54:27,504 - INFO - Starting
2011-06-15 11:56:09,114 - INFO - Starting
2011-06-15 12:03:06,459 - INFO - Starting
2011-06-15 12:03:55,236 - ERROR - Get failure
Traceback (most recent call last):
  File "flunkymaster.py", line 220, in __call__
    template = self.render_image_path(address, path)
  File "flunkymaster.py", line 181, in render_image_path
    bvars = self.build_vars(address, toRender)
  File "flunkymaster.py", line 113, in build_vars
    self.staticBuild[address]['IMAGE'] = self.data[address]['Image']
KeyError: '127.0.0.1'
2011-06-15 12:04:34,965 - ERROR - Get failure
Traceback (most recent call last):
  File "flunkymaster.py", line 220, in __call__
    template = self.render_image_path(address, path)
  File "flunkymaster.py", line 181, in render_image_path
    bvars = self.build_vars(address, toRender)
  File "flunkymaster.py", line 113, in build_vars
    self.staticBuild[address]['IMAGE'] = self.data[address]['Image']
KeyError: '127.0.0.1'
2011-06-15 12:06:42,065 - INFO - Starting
2011-06-15 12:06:44,206 - ERROR - Get failure
Traceback (most recent call last):
  File "flunkymaster.py", line 220, in __call__
    template = self.render_image_path(address, path)
  File "flunkymaster.py", line 181, in render_image_path
    bvars = self.build_vars(address, toRender)
  File "flunkymaster.py", line 114, in build_vars
    self.staticBuild[address]['BUILDSERVER'] = self.flunkyURL
KeyError: '127.0.0.1'
2011-06-15 12:07:26,788 - INFO - Starting
2011-06-15 12:07:29,906 - ERROR - Get failure
Traceback (most recent call last):
  File "flunkymaster.py", line 220, in __call__
    template = self.render_image_path(address, path)
  File "flunkymaster.py", line 181, in render_image_path
    bvars = self.build_vars(address, toRender)
  File "flunkymaster.py", line 115, in build_vars
    data.append(self.staticBuild)
AttributeError: 'dict' object has no attribute 'append'
2011-06-15 12:11:37,107 - INFO - Starting
2011-06-15 12:16:43,155 - INFO - Starting
